Console.WriteLine("Введите первое число...");
var numA = int.Parse(Console.ReadLine());
Console.WriteLine("Введите второе число...");
var numB = int.Parse(Console.ReadLine());
int result = numA + numB;
Console.Write(numA);
Console.Write(" + ");
Console.Write(numB);
Console.Write(" = ");
Console.Write(result);